# Generated by Django 4.2.3 on 2023-10-29 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cart_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
